image: maven:3.3.9-jdk-8

variables:
  MAVEN_OPTS: -Dmaven.repo.local=/cache/maven.repository

stages:
  - build
  - bugfix
  - release

.build_template: &build_definition 
  script:
    - "mvn compile test package "
  when: manual
  
nightly_build:
   <<: *build_definition
   stage: build
   only:
    - develop
 
start_release:
   <<: *build_definition
   stage: bugfix
   only:
    - develop

publish_bugfix:
   <<: *build_definition
   stage: bugfix
   only:
    - preprod

end_release:
   <<: *build_definition
   stage: release
   only:
    - preprod
