image: maven:3.3.9-jdk-8

stages:
  - nightly_build
  - start_release
  - start_bugfix
  - end_bugfix
  - end_release


.build_template: &build_definition 
  script:
    - "mvn compile test package "
  when: manual
  
nightly_build:  
  only:
    - develop
    
start_release:
  only:
    - develop
    
start_bugfix
  only:
    - preprod
    
end_bugfix
  only:
    - preprod
    
end_release:
  only:
    - preprod
