image: maven:3.3.9-jdk-8

stages:
  - nightly_build
  - start_release
  - start_bugfix
  - end_bugfix
  - end_release


.build_template: &build_definition 
  script:
    - "mvn compile test package "
  when: manual
  
nightly_build:
  <<: *build_definition 
  only:
    - develop
    
start_release:
  <<: *build_definition 
  only:
    - develop
    
start_bugfix:
  <<: *build_definition 
  only:
    - preprod
    
end_bugfix:
  <<: *build_definition 
  only:
    - preprod
    
end_release:
  <<: *build_definition 
  only:
    - preprod
